
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[327] =
    {   0,
        0,    0,   77,   76,   74,   75,   76,   72,   76,   72,
       72,   76,   72,   72,   72,   72,   72,   72,   68,   68,
       72,   32,   72,   46,   72,   71,   47,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       72,   74,   73,   54,    0,   59,    0,   39,   48,   42,
       57,    0,    0,   60,    0,   37,   52,   33,   53,   68,
       68,   34,    0,    0,   69,    0,    0,   38,   69,   63,
       64,   64,   66,   66,   66,    0,    0,   68,   61,   68,
        0,   68,   44,   31,   50,   56,   45,   55,   51,   71,
       36,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       17,   19,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   35,   49,    0,   59,    0,
       43,    0,    1,    0,   62,   60,   62,    0,    0,    0,
        0,   58,   69,    0,   69,    0,    0,    0,    0,    2,
        0,    0,   69,    0,   63,   64,   64,   66,   63,   64,
       66,    0,   66,   65,    0,    0,   66,    0,   69,   40,
       41,   71,   71,   71,   71,   71,   71,   71,   15,   71,
       71,   71,   71,   71,   21,   71,   71,   71,   71,   71,
       71,   71,   71,   28,   60,    0,   62,    0,    0,    0,
        0,    0,    0,   69,    3,    0,    0,   69,   69,    0,

       69,   63,   64,   66,   66,   65,   67,    0,    0,   66,
       69,   69,   71,    7,    8,   71,   71,   71,   71,   13,
       71,   71,   16,   18,   71,   71,   30,   71,   71,   71,
       71,   71,   71,   29,   27,    0,   62,   62,    0,   62,
       69,   69,   69,   69,   67,   67,    0,    0,   70,    6,
        9,   71,   71,   12,   71,   71,   71,   71,   22,   71,
       71,   71,   71,    0,   62,    0,    0,   67,    0,   70,
       70,   71,   71,   71,   71,   71,   71,   23,   24,   25,
       26,    0,   62,   71,   11,   71,    0,    0,    0,   71,
       71,    0,   10,   71,    0,    4,    0,    0,    0,   71,

        0,    0,   71,    0,    0,    4,    0,    0,    0,    0,
        0,   20,    5,    0,   71,    0,    0,    0,    0,    0,
        0,    5,   14,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   30,   30,   32,   30,
       33,   33,   33,   33,   33,   33,   33,   33,   34,   35,
       33,   33,   33,   33,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   33,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    3,    3,    1,    1,    1,    1,    4,    1,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    7,    7,    8,    7,    7,    9,    9,    9,
        9,   10,    9,    6,    6,    6,    6,    6,    6,    7,
        7,   11,    7,    7,    7,    7,    7,    8,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[347] =
    {   0,
        0,    0,  875, 1368,   69, 1368,  871,  844,   64,  843,
       63,   71, 1368,  842,   61,   64,   75,   75,   93,  111,
      837, 1368,   82,  835,   50,    0,  834,  801,   61,  811,
      794,   92,  790,  111,  801,  794,   35,   58,   41,  790,
       53,  142, 1368, 1368,  112, 1368,  144, 1368, 1368, 1368,
      806,  117,  135, 1368,  181, 1368, 1368, 1368, 1368,    0,
      158, 1368,  149,  814,  213,  143,  152, 1368,  230,  151,
      144,  177,  135,  237,  249,  253,  176,  789, 1368,  265,
      279,  288, 1368, 1368,  803, 1368, 1368, 1368,  802,    0,
     1368,  770,  757,  772,  759,  765,  751,  756,  750,  748,

      741,    0,  743,  739,  738,  730,  740,  723,  717,  720,
      714,  720,  709,  711,  699, 1368, 1368,  199,  215,  273,
     1368,  228, 1368,  210,  245,  266,  330,  360,  407,  437,
      467, 1368,  306,  301,  311,  195,  249,  279,  202, 1368,
      300,  324,  392,  350,  715,  374,  713,  180,  712,  377,
      711,  364,  379,  421,  335,    0,  475,  206,  454, 1368,
     1368,  700,  695,  685,  254,  320,  692,  265,    0,  693,
      671,  657,  665,  667,    0,  657,  653,  629,  637,  609,
      607,  619,  599,    0,  378,  422,    0,  514,  544,  574,
      604,  634,  427,  480, 1368,  327,  393,  652,  520,  498,

      527,  602,  596,    0,  591,  487,  634,  353,  508,  586,
      560,  533,  558,    0,    0,  542,  535,  522,  519,    0,
      516,  525,    0,    0,  512,  511,    0,  513,  503,  479,
      478,  459,  458,    0,    0,  685,  715,  745,  775,  392,
      587,  578,  667,  593,  452,  660,  620,  676,  700,    0,
        0,  436,  437,    0,  429,  418,  429,  415,    0,  389,
      375,  374,  372,  805,  835,  865,  895,  351,  638,  728,
      704,  287,  281,  278,  414,  248,  242,    0,    0,    0,
        0,  925,  955,  232,    0,  158,  458,  296,  779,  149,
      169,  985,    0,  111,  487, 1368,  800,  838,  578,  113,

      120, 1015,   67,  860,  623,  890,  459,  920,  624, 1063,
      950,    0,    0, 1057,   50,  980, 1105,  638, 1117,  662,
     1010,    0,    0, 1129, 1141, 1368, 1180, 1191, 1198, 1209,
     1220, 1231, 1242, 1249, 1257, 1267, 1278, 1285, 1287, 1295,
     1306, 1317, 1327, 1338, 1349, 1356
    } ;

static const flex_int16_t yy_def[347] =
    {   0,
      326,    1,  326,  326,  326,  326,  326,  326,  327,  326,
      326,  328,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  329,  326,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      326,  326,  326,  326,  327,  326,  330,  326,  326,  326,
      326,  328,  328,  326,  331,  326,  326,  326,  326,   19,
      326,  326,  326,  326,  326,  332,  333,  326,  326,   19,
       70,   70,  334,  334,   74,  326,  335,   70,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  329,
      326,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  326,  326,  327,  327,  330,
      326,  331,  326,  328,  328,  328,  328,  127,  331,  127,
      127,  326,  326,  326,  326,  332,  336,  332,  333,  326,
      337,  326,  326,  326,   70,   70,   72,  334,   74,   74,
       74,  326,   74,  326,  326,  338,  335,  335,  326,  326,
      326,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  328,  331,  127,  127,  127,  127,
      127,  127,  326,  326,  326,  333,  337,  326,  326,  326,

      326,   74,  150,  153,  153,  326,  338,  339,  326,  157,
      326,  326,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  127,  127,  127,  127,  328,
      326,  326,  326,  326,  207,  339,  326,  326,  326,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  127,  127,  127,  127,  246,  326,  326,
      326,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  127,  127,  329,  329,  329,  326,  340,  326,  329,
      329,  127,  329,  329,  340,  326,  341,  326,  342,  329,

      343,  127,  329,  341,  340,  341,  344,  341,  342,  326,
      345,  329,  346,  127,  329,  341,  326,  342,  342,  342,
      345,  346,  329,  342,  342,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326
    } ;

static const flex_int16_t yy_nxt[1439] =
    {   0,
        4,    5,    6,    4,    7,    5,    8,    9,   10,   11,
       12,   13,   13,   14,   15,   13,   16,   17,   18,   19,
       20,   20,   20,   21,   22,   23,   24,   25,   13,   26,
       26,   26,   26,   26,   26,   26,   26,   13,    4,   13,
       27,   26,    4,   26,   28,   29,   30,   31,   32,   33,
       26,   34,   26,   26,   35,   26,   26,   36,   37,   38,
       39,   26,   40,   26,   26,   26,   13,   41,   13,   13,
       42,   46,   49,   53,   42,   57,   88,   89,  108,  116,
       59,   54,  109,   60,   61,   61,   61,   58,   66,   50,
       62,   63,   64,   67,   65,   65,   65,   65,   84,  113,

      323,   68,   47,   51,   93,  110,  114,   85,   86,   55,
       69,   94,   70,   70,   71,   72,  315,   95,  111,   46,
      117,  112,   73,   74,   75,  301,   76,   54,   69,   77,
       80,   80,   80,   80,   78,   98,   73,   74,   73,   73,
       75,   73,   81,   42,   79,  123,   45,   42,   99,   76,
       47,  119,   82,  100,  140,  122,  137,   77,   81,  102,
      312,  138,   79,   71,   71,  103,  104,  105,   65,   65,
       65,   65,  303,  122,  301,   69,  148,   80,   80,   80,
       80,   73,  120,   52,  326,  146,   79,  326,  125,   81,
      141,  126,  145,  156,  300,   73,   72,   72,   72,   82,

      127,  127,  127,  127,  140,   81,   46,  326,  137,   79,
      127,  127,  127,  138,  294,  326,  128,  158,  147,  129,
       54,  326,   46,  326,  127,  127,  127,  127,  127,  127,
       52,   79,  133,  133,  133,  133,  125,   47,  185,  125,
      141,  125,  130,  125,  134,  131,  142,  326,  122,  143,
      143,  143,  143,   47,  135,   54,  149,  149,  150,  150,
      134,  144,  137,  152,   79,  152,  186,  195,  153,  153,
      153,  153,  154,  154,  154,   45,   54,  144,  151,  293,
      119,   79,   69,  122,   80,   80,   80,   80,   79,  291,
      148,  290,  137,  152,  155,  152,   81,  138,  159,  159,

      159,  159,  140,  296,  122,   69,   82,   80,   80,   80,
       80,  120,   81,  216,  217,  193,   79,  193,  221,   81,
      194,  194,  194,  194,  222,  133,  133,  133,  133,  140,
      133,  133,  133,  133,  297,   81,  286,  134,  197,   79,
       54,  285,  134,  143,  143,  143,  143,  135,  284,  187,
      187,  187,  187,  134,  154,  154,  154,   79,  134,  187,
      187,  187,   79,  218,  200,  141,  200,  219,  122,  201,
      201,  201,  201,  187,  187,  187,  187,  187,  187,  188,
      188,  188,  188,  159,  159,  159,  159,  209,   54,  188,
      188,  188,  326,   71,   71,  140,  150,  150,  204,  204,

      204,  204,   54,  188,  188,  188,  188,  188,  188,   52,
      209,  198,  198,  198,  198,  326,  122,  185,  203,  287,
      205,  288,  281,  144,   52,  289,  189,  189,  189,  190,
      122,  197,  185,  199,  280,  279,  190,  190,  190,  144,
      154,  154,  154,   79,  278,  186,  194,  194,  194,  194,
      190,  190,  190,  190,  190,  190,  191,  191,  191,  191,
      186,  295,  206,  287,  277,  288,  191,  191,  191,  289,
      307,  307,   79,  211,  211,  211,  211,  276,  275,  274,
      191,  191,  191,  191,  191,  191,  192,  192,  192,  192,
      273,  272,  208,  326,  296,  212,  192,  192,  192,  241,

      241,  241,  241,  263,  262,   79,  154,  154,  154,  209,
      192,  192,  192,  192,  192,  192,  210,  201,  201,  201,
      201,  242,  247,  261,  248,  297,   79,  249,  249,  249,
      249,   79,  209,  236,  236,  236,  236,  260,   79,  198,
      198,  198,  198,  236,  236,  236,  243,  243,  243,  243,
      259,  144,  211,  211,  211,  211,  258,  236,  236,  236,
      236,  236,  236,  237,  237,  237,  238,  144,  244,  257,
      256,   79,  234,  238,  238,  238,  255,  254,   79,  211,
      211,  211,  211,  253,   79,  310,  252,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  241,  241,  241,

      241,  212,  251,  238,  238,  238,  241,  241,  241,  241,
      250,   79,  243,  243,  243,  243,  311,  238,  238,  238,
      238,  238,  238,  239,  239,  239,  239,  326,  242,   79,
      296,  310,  326,  239,  239,  239,  269,  326,   79,  249,
      249,  249,  249,  326,   79,  310,  235,  239,  239,  239,
      239,  239,  239,  240,  240,  240,  240,  249,  249,  249,
      249,  297,  311,  240,  240,  240,  234,  233,  209,  310,
      232,  198,  198,  198,  198,  245,  311,  240,  240,  240,
      240,  240,  240,  144,  231,   79,  243,  243,  243,  243,
      230,  209,  269,  199,  209,  249,  249,  249,  249,  144,

      311,  268,  229,   79,  264,  264,  264,  264,  244,  228,
      227,   79,  226,  225,  264,  264,  264,  209,   79,  270,
      270,  270,  270,  270,  270,  270,  270,  224,  264,  264,
      264,  264,  264,  264,  265,  265,  265,  266,  223,  220,
      215,  271,  214,  213,  266,  266,  266,  270,  270,  270,
      270,   79,  326,  202,  326,   79,  326,  184,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  183,  271,
      182,  181,  180,  179,  266,  266,  266,  178,  177,   79,
      298,  298,  298,  298,  298,  176,  299,  175,  266,  266,
      266,  266,  266,  266,  267,  267,  267,  267,  174,  173,

      172,  171,  305,  170,  267,  267,  267,  306,  169,  168,
      167,  307,  307,  166,  165,  164,  163,  162,  267,  267,
      267,  267,  267,  267,  282,  282,  282,  282,  161,  160,
      326,  132,  121,  115,  282,  282,  282,  107,  308,  298,
      298,  298,  298,  298,  106,  299,  101,   97,  282,  282,
      282,  282,  282,  282,  283,  283,  283,  283,   96,   92,
       91,   87,  305,   83,  283,  283,  283,  306,   56,   48,
       44,  307,  307,   43,  326,  326,  326,  326,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  326,  326,
      326,  326,  305,  326,  283,  283,  283,  306,  308,  326,

      326,  307,  307,  326,  326,  326,  326,  326,  283,  283,
      283,  283,  283,  283,  240,  240,  240,  240,  326,  326,
      326,  326,  305,  326,  240,  240,  240,  306,  308,  326,
      326,  307,  307,  326,  326,  326,  326,  326,  240,  240,
      240,  240,  240,  240,  292,  292,  292,  292,  326,  326,
      326,  326,  309,  326,  292,  292,  292,  319,  308,  326,
      326,  320,  320,  326,  326,  326,  326,  326,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  326,  326,
      326,  326,  305,  326,  292,  292,  292,  306,  321,  326,
      326,  307,  307,  326,  326,  326,  326,  326,  292,  292,

      292,  292,  292,  292,  302,  302,  302,  302,  326,  326,
      326,  326,  309,  326,  302,  302,  302,  319,  308,  326,
      326,  320,  320,  326,  326,  326,  326,  326,  302,  302,
      302,  302,  302,  302,  314,  314,  314,  314,  326,  326,
      326,  326,  326,  326,  314,  314,  314,  326,  321,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  314,  314,
      314,  314,  314,  314,  317,  317,  317,  317,  317,  326,
      299,  326,  326,  326,  326,  296,  240,  240,  240,  240,
      326,  326,  326,  326,  326,  326,  240,  240,  240,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      240,  240,  240,  240,  240,  240,  317,  317,  317,  317,
      317,  326,  299,  326,  326,  326,  326,  296,  324,  324,
      324,  324,  324,  326,  325,  326,  326,  326,  326,  296,
      324,  324,  324,  324,  324,  326,  325,  326,  326,  326,
      326,  296,  324,  324,  324,  324,  324,  326,  325,  326,
      326,  326,  326,  296,  326,  311,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  311,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  311,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   90,   90,   90,   90,  326,   90,   90,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,   73,   73,  326,  326,  326,   73,   73,
      157,  157,  157,  326,  326,  326,  157,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  207,
      207,  246,  246,  326,  246,  295,  295,  326,  295,  295,

      295,  295,  295,  295,  295,  295,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  309,  309,  326,
      309,  309,  309,  309,  309,  309,  309,  309,  313,  326,
      326,  326,  313,  313,  313,  313,  313,  313,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      322,  322,  322,  322,  322,  322,  322,    3,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326
    } ;

static const flex_int16_t yy_chk[1439] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    9,   11,   12,    5,   15,   25,   25,   37,   41,
       16,   12,   37,   16,   16,   16,   16,   15,   18,   11,
       16,   17,   17,   18,   17,   17,   17,   17,   23,   39,

      315,   18,    9,   11,   29,   38,   39,   23,   23,   12,
       19,   29,   19,   19,   19,   19,  303,   29,   38,   45,
       41,   38,   19,   19,   19,  301,   19,   52,   20,   19,
       20,   20,   20,   20,   19,   32,   19,   19,   19,   19,
       19,   19,   20,   42,   19,   53,   47,   42,   32,   19,
       45,   47,   20,   32,   67,   52,   66,   19,   20,   34,
      300,   66,   20,   71,   71,   34,   34,   34,   63,   63,
       63,   63,  294,   53,  291,   61,   73,   61,   61,   61,
       61,   70,   47,   55,   70,   71,   73,   70,   55,   61,
       67,   55,   70,   77,  290,   70,   72,   72,   72,   61,

       55,   55,   55,   55,  139,   61,  118,   70,  136,   61,
       55,   55,   55,  136,  286,   70,   55,   77,   72,   55,
      124,  148,  119,  158,   55,   55,   55,   55,   55,   55,
      122,  148,   65,   65,   65,   65,   55,  118,  122,   55,
      139,   55,   55,   55,   65,   55,   69,  158,  124,   69,
       69,   69,   69,  119,   65,  125,   74,   74,   74,   74,
       65,   69,  137,   75,   65,   75,  122,  137,   75,   75,
       75,   75,   76,   76,   76,  120,  126,   69,   74,  284,
      120,   69,   80,  125,   80,   80,   80,   80,   74,  277,
       75,  276,  138,   81,   76,   81,   80,  138,   81,   81,

       81,   81,  141,  288,  126,   82,   80,   82,   82,   82,
       82,  120,   80,  165,  165,  134,   80,  134,  168,   82,
      134,  134,  134,  134,  168,  133,  133,  133,  133,  196,
      135,  135,  135,  135,  288,   82,  274,  133,  141,   82,
      127,  273,  135,  142,  142,  142,  142,  133,  272,  127,
      127,  127,  127,  133,  155,  155,  155,  133,  135,  127,
      127,  127,  135,  166,  144,  196,  144,  166,  127,  144,
      144,  144,  144,  127,  127,  127,  127,  127,  127,  128,
      128,  128,  128,  152,  152,  152,  152,  208,  185,  128,
      128,  128,  268,  146,  146,  197,  150,  150,  153,  153,

      153,  153,  240,  128,  128,  128,  128,  128,  128,  129,
      208,  143,  143,  143,  143,  146,  185,  129,  150,  275,
      153,  275,  263,  143,  186,  275,  129,  129,  129,  129,
      240,  197,  186,  143,  262,  261,  129,  129,  129,  143,
      154,  154,  154,  143,  260,  129,  193,  193,  193,  193,
      129,  129,  129,  129,  129,  129,  130,  130,  130,  130,
      186,  307,  154,  287,  258,  287,  130,  130,  130,  287,
      307,  307,  154,  159,  159,  159,  159,  257,  256,  255,
      130,  130,  130,  130,  130,  130,  131,  131,  131,  131,
      253,  252,  157,  245,  295,  159,  131,  131,  131,  194,

      194,  194,  194,  233,  232,  159,  206,  206,  206,  157,
      131,  131,  131,  131,  131,  131,  157,  200,  200,  200,
      200,  194,  209,  231,  209,  295,  157,  209,  209,  209,
      209,  194,  157,  188,  188,  188,  188,  230,  206,  199,
      199,  199,  199,  188,  188,  188,  201,  201,  201,  201,
      229,  199,  212,  212,  212,  212,  228,  188,  188,  188,
      188,  188,  188,  189,  189,  189,  189,  199,  201,  226,
      225,  199,  222,  189,  189,  189,  221,  219,  201,  211,
      211,  211,  211,  218,  212,  299,  217,  189,  189,  189,
      189,  189,  189,  190,  190,  190,  190,  242,  242,  242,

      242,  211,  216,  190,  190,  190,  241,  241,  241,  241,
      213,  211,  244,  244,  244,  244,  299,  190,  190,  190,
      190,  190,  190,  191,  191,  191,  191,  210,  241,  242,
      305,  309,  205,  191,  191,  191,  247,  203,  241,  247,
      247,  247,  247,  202,  244,  318,  183,  191,  191,  191,
      191,  191,  191,  192,  192,  192,  192,  269,  269,  269,
      269,  305,  309,  192,  192,  192,  182,  181,  207,  320,
      180,  198,  198,  198,  198,  207,  318,  192,  192,  192,
      192,  192,  192,  198,  179,  207,  243,  243,  243,  243,
      178,  207,  248,  198,  246,  248,  248,  248,  248,  198,

      320,  246,  177,  198,  236,  236,  236,  236,  243,  176,
      174,  246,  173,  172,  236,  236,  236,  246,  243,  249,
      249,  249,  249,  271,  271,  271,  271,  171,  236,  236,
      236,  236,  236,  236,  237,  237,  237,  237,  170,  167,
      164,  249,  163,  162,  237,  237,  237,  270,  270,  270,
      270,  249,  151,  149,  147,  271,  145,  115,  237,  237,
      237,  237,  237,  237,  238,  238,  238,  238,  114,  270,
      113,  112,  111,  110,  238,  238,  238,  109,  108,  270,
      289,  289,  289,  289,  289,  107,  289,  106,  238,  238,
      238,  238,  238,  238,  239,  239,  239,  239,  105,  104,

      103,  101,  297,  100,  239,  239,  239,  297,   99,   98,
       97,  297,  297,   96,   95,   94,   93,   92,  239,  239,
      239,  239,  239,  239,  264,  264,  264,  264,   89,   85,
       78,   64,   51,   40,  264,  264,  264,   36,  297,  298,
      298,  298,  298,  298,   35,  298,   33,   31,  264,  264,
      264,  264,  264,  264,  265,  265,  265,  265,   30,   28,
       27,   24,  304,   21,  265,  265,  265,  304,   14,   10,
        8,  304,  304,    7,    3,    0,    0,    0,  265,  265,
      265,  265,  265,  265,  266,  266,  266,  266,    0,    0,
        0,    0,  306,    0,  266,  266,  266,  306,  304,    0,

        0,  306,  306,    0,    0,    0,    0,    0,  266,  266,
      266,  266,  266,  266,  267,  267,  267,  267,    0,    0,
        0,    0,  308,    0,  267,  267,  267,  308,  306,    0,
        0,  308,  308,    0,    0,    0,    0,    0,  267,  267,
      267,  267,  267,  267,  282,  282,  282,  282,    0,    0,
        0,    0,  311,    0,  282,  282,  282,  311,  308,    0,
        0,  311,  311,    0,    0,    0,    0,    0,  282,  282,
      282,  282,  282,  282,  283,  283,  283,  283,    0,    0,
        0,    0,  316,    0,  283,  283,  283,  316,  311,    0,
        0,  316,  316,    0,    0,    0,    0,    0,  283,  283,

      283,  283,  283,  283,  292,  292,  292,  292,    0,    0,
        0,    0,  321,    0,  292,  292,  292,  321,  316,    0,
        0,  321,  321,    0,    0,    0,    0,    0,  292,  292,
      292,  292,  292,  292,  302,  302,  302,  302,    0,    0,
        0,    0,    0,    0,  302,  302,  302,    0,  321,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  302,  302,
      302,  302,  302,  302,  310,  310,  310,  310,  310,    0,
      310,    0,    0,    0,    0,  310,  314,  314,  314,  314,
        0,    0,    0,    0,    0,    0,  314,  314,  314,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      314,  314,  314,  314,  314,  314,  317,  317,  317,  317,
      317,    0,  317,    0,    0,    0,    0,  317,  319,  319,
      319,  319,  319,    0,  319,    0,    0,    0,    0,  319,
      324,  324,  324,  324,  324,    0,  324,    0,    0,    0,
        0,  324,  325,  325,  325,  325,  325,    0,  325,    0,
        0,    0,    0,  325,    0,  319,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  324,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  325,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  329,  329,  329,  329,    0,  329,  329,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  332,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  334,  334,    0,    0,    0,  334,  334,
      335,  335,  335,    0,    0,    0,  335,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  338,
      338,  339,  339,    0,  339,  340,  340,    0,  340,  340,

      340,  340,  340,  340,  340,  340,  341,  341,  341,  341,
      341,  341,  341,  341,  341,  341,  341,  342,  342,    0,
      342,  342,  342,  342,  342,  342,  342,  342,  343,    0,
        0,    0,  343,  343,  343,  343,  343,  343,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  345,
      345,  345,  345,  345,  345,  345,  345,  345,  345,  345,
      346,  346,  346,  346,  346,  346,  346,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[77] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lab2.lex"
#line 2 "lab2.lex"
    #include <iostream>
	#include "y.tab.h"
	void yyerror(const char *s);
    int line_counter = 0;
	// [a-zA-z]*((\.[a-zA-z]+))+				{return METHOD;}
	/*
	"any"									{return ANYTYPE;}
"bool"									{return BOOL_TYPE;}
"byte"									{return BYTE;}
"comparable"							{return COMPARABLE;}
"string"								{return STRING;}
"complex"((64)|(128))					{return COMPLEXTYPE;}
"error"									{return ERRORTYPE;}
"uint"((8)|(16)|(32)|(64))? 			{return UINT;}
"uintptr"								{return UINTPTR;}
"int"((8)|(16)|(32)|(64))?				{return INT;}
"float"((32)|(64))						{return FLOAT;}
"rune"									{return RUNE;}
	
	*/
	
#line 922 "lex.yy.c"
#line 923 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "lab2.lex"

#line 1142 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1368 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 29 "lab2.lex"
{line_counter++;yylval++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 30 "lab2.lex"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 31 "lab2.lex"
; 
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 33 "lab2.lex"
{return IMPORTS;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "lab2.lex"
{return PACKAGE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "lab2.lex"
{return BREAK;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "lab2.lex"
{return CASE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "lab2.lex"
{return CHAN;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "lab2.lex"
{return CONST;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "lab2.lex"
{return CONTINUE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "lab2.lex"
{return DEFAULT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "lab2.lex"
{return DEFER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "lab2.lex"
{return ELSE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "lab2.lex"
{return FALLTHROUGH;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 44 "lab2.lex"
{return FOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "lab2.lex"
{return FUNCTION;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 46 "lab2.lex"
{return GO;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 47 "lab2.lex"
{return GOTO;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 48 "lab2.lex"
{return IF;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 49 "lab2.lex"
{return INTERFACE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "lab2.lex"
{return MAP;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "lab2.lex"
{return RANGE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "lab2.lex"
{return RETURN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "lab2.lex"
{return SELECT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "lab2.lex"
{return STRUCT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "lab2.lex"
{return SWITCH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "lab2.lex"
{return TYPE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "lab2.lex"
{return VAR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "lab2.lex"
{return BOOL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "lab2.lex"
{return IOTA;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "lab2.lex"
{return POINTER;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "lab2.lex"
{return SEMICOLON;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "lab2.lex"
{return ADDEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "lab2.lex"
{return DECEQ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "lab2.lex"
{return OREQ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "lab2.lex"
{return XOREQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "lab2.lex"
{return MULEQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "lab2.lex"
{return DIVEQ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "lab2.lex"
{return MODEQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "lab2.lex"
{return LSHIFTEQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "lab2.lex"
{return RSHIFTEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "lab2.lex"
{return ANDEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "lab2.lex"
{return ANDXOREQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "lab2.lex"
{return PEQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "lab2.lex"
{return EQUAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "lab2.lex"
{return EQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "lab2.lex"
{return XOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "lab2.lex"
{return AND;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "lab2.lex"
{return OR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "lab2.lex"
{return LSHIFT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "lab2.lex"
{return RSHIFT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "lab2.lex"
{return INC;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "lab2.lex"
{return DEC;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "lab2.lex"
{return NOTEQUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "lab2.lex"
{return GREATEROREQUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "lab2.lex"
{return LESSOREQUAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "lab2.lex"
{return AMP_EXP;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "lab2.lex"
{return POINT;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 98 "lab2.lex"
{return CONST_STRING;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 99 "lab2.lex"
{return CONST_CHAR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "lab2.lex"
{return IMAGINARY_LIT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "lab2.lex"
{return RUNE_LIT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "lab2.lex"
{return CONST_BIN;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "lab2.lex"
{return CONST_BIN_ERR;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "lab2.lex"
{return CONST_OCTAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "lab2.lex"
{return CONST_HEX;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "lab2.lex"
{return FLOAT_HEX;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "lab2.lex"
{return CONST_INT;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "lab2.lex"
{return DECIMAL_FLOAT_LIT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "lab2.lex"
{return HEX_FLOAT_LIT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "lab2.lex"
{return id;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 119 "lab2.lex"
{return yytext[0];}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 120 "lab2.lex"
{yylval++;line_counter++;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "lab2.lex"
/* empty */
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 122 "lab2.lex"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "lab2.lex"
ECHO;
	YY_BREAK
#line 1597 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 326);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 123 "lab2.lex"


